.PHONY: up down logs build

# Build the application
build:
	docker-compose build

# Start Docker containers
up:
	docker-compose up -d

# Stop Docker containers
down:
	docker-compose down

# View Docker logs
logs:
	docker-compose logs -f app

